# Generated by Django 5.1.6 on 2025-02-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Name Book')),
                ('pages', models.IntegerField(verbose_name='Pages in Book')),
                ('page_now', models.IntegerField(verbose_name='Page Now')),
                ('bookmarks', models.JSONField(default=list, verbose_name='Bookmarks')),
            ],
        ),
    ]
